// ./pages/_document.js
import React from "react";
import Document, { Html, Head, Main, NextScript } from "next/document";
import { ServerStyleSheet } from "styled-components";

class MyDocument extends Document {
	render() {
		const sheet = new ServerStyleSheet();
		const main = sheet.collectStyles(<Main />);
		const styleTags = sheet.getStyleElement();
		return (
			<Html>
				<Head>
					<title>Profile me</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />

					<link
						href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
						rel="stylesheet"
					/>
					<link
						rel="stylesheet"
						href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@48,400,0,0"
					/>
					<link rel="stylesheet" href="/static/css/style.css" />
					<link
						rel="stylesheet"
						href="/static/vendor/node_modules/bootstrap/dist/css/bootstrap.min.css"
					/>
					<link
						rel="stylesheet"
						href="/static/vendor/node_modules/owl.carousel/dist/assets/owl.carousel.min.css"
					/>
					<link
						rel="stylesheet"
						href="/static/vendor/node_modules/owl.carousel/dist/assets/owl.theme.default.min.css"
					/>

					{styleTags}
				</Head>
				<body>
					{main}
					<NextScript />
				</body>
			</Html>
		);
	}
}

export default MyDocument;
