import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Carousel } from "react-responsive-carousel";
import { LeaderboardRoundedIcon } from "@mui/icons-material";

const Home = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Profile me</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div>
				<div className={styles.titleContent}>
					<div>
						<h1 className={styles.title}>All my accounts</h1>
						<div>June 10 2018</div>
					</div>
					<div>
						<span className="material-symbols-rounded">equalizer</span>
					</div>
				</div>
				<div
					style={{
						display: "flex",
						flexDirection: "row",
						alignItems: "center",
					}}
				>
					<div
						style={{
							display: "flex",
							flexDirection: "column",
							alignItems: "center",
							width: "50%",
						}}
					>
						<div
							style={{
								margin: `8px 0px`,
								fontWeight: "bold",
								fontSize: "14px",
							}}
						>
							Income
						</div>
						<div
							style={{
								display: "flex",
								flexDirection: "row",
								alignItems: "center",
								justifyContent: "center",
								color: "#42B84F",
								fontSize: "18px",
							}}
						>
							<span className="material-symbols-rounded">arrow_downward</span>
							<div style={{ marginLeft: "8px" }}>$9,302.00</div>
						</div>
					</div>
					<div
						style={{
							display: "flex",
							flexDirection: "column",
							alignItems: "center",
							width: "50%",
						}}
					>
						<div
							style={{
								margin: `8px 0px`,
								fontWeight: "bold",
								fontSize: "14px",
							}}
						>
							Expense
						</div>
						<div
							style={{
								display: "flex",
								flexDirection: "row",
								alignItems: "center",
								justifyContent: "center",
								color: "red",
								fontSize: "18px",
							}}
						>
							<span className="material-symbols-rounded">arrow_upward</span>
							<div style={{ marginLeft: "8px" }}>$2,790.00</div>
						</div>
					</div>
				</div>
				<div
					style={{
						display: "flex",
						flexDirection: "row",
						alignItems: "center",
						justifyContent: "space-between",
						margin: "16px 0px",
					}}
				>
					<div style={{ fontSize: 24, fontWeight: "normal" }}>
						Detail of movements
					</div>
					<span className="material-symbols-rounded">today</span>
				</div>
				{/* /// */}
				<div
					style={{
						display: "flex",
						flexDirection: "row",
						alignItems: "center",
						justifyContent: "space-between",
						margin: "16px 0px",
					}}
				>
					<div
						style={{
							display: "flex",
							flexDirection: "row",
							alignItems: "center",
							width: "80%",
						}}
					>
						<div style={{ width: "20%" }}>
							<span className="material-symbols-rounded">restaurant</span>
						</div>
						<div
							style={{
								display: "flex",
								flexDirection: "column",
							}}
						>
							<div>Restaurant Manhattan</div>
							<div>June 10 2018</div>
						</div>
					</div>
					<div
						style={{
							width: "20%",
							display: "flex",
							flexDirection: "row",
							alignItems: "center",
							justifyContent: "center",
							color: "red",
							fontSize: "18px",
						}}
					>
						<div style={{ marginLeft: "8px" }}>$170</div>
						<span className="material-symbols-rounded">arrow_upward</span>
					</div>
				</div>

				<div
					style={{
						display: "flex",
						flexDirection: "row",
						alignItems: "center",
						justifyContent: "space-between",
					}}
				>
					<div
						style={{
							display: "flex",
							flexDirection: "row",
							alignItems: "center",
							width: "80%",
						}}
					>
						<div style={{ width: "20%" }}>
							<span className="material-symbols-rounded">restaurant</span>
						</div>
						<div
							style={{
								display: "flex",
								flexDirection: "column",
							}}
						>
							<div>Salary Deposit</div>
							<div>June 10 2018</div>
						</div>
					</div>
					<div
						style={{
							width: "20%",
							display: "flex",
							flexDirection: "row",
							alignItems: "center",
							justifyContent: "center",
							color: "#42B84F",
							fontSize: "18px",
						}}
					>
						<div style={{ marginLeft: "8px" }}>$1,200</div>
						<span className="material-symbols-rounded">arrow_downward</span>
					</div>
				</div>
			</div>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{" "}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
};

export default Home;
